@startuml

skinparam activityShape octagon

title Activity Diagram\nMengelola Satuan & Konversi

start
:Bagian Inventori mengakses halaman satuan;
:Sistem menampilkan daftar satuan;

if (Jenis Satuan?) then (Satuan Dasar)
    :Menambah satuan baru;
    :Tanpa faktor konversi;
    :Contoh: gram, ml, pcs;
else (Satuan Turunan)
    :Menambah satuan turunan;
    :Memilih satuan dasar;
    :Memasukkan faktor konversi;
    :Contoh: kg (1000 gram);
endif

:Menyimpan data satuan;
:Sistem memvalidasi relasi satuan;
stop

@enduml
