@startuml

skinparam linetype ortho
hide circle

title ERD - Increment 2\nModul Pendukung Operasional

' ==========================================
' ENTITAS INVENTORI (INCREMENT 2)
' ==========================================

entity "materials" as materials {
    *id : UUID <<PK>>
    --
    name : VARCHAR(50)
    description : VARCHAR(255)
    image : VARCHAR(255)
    expiry_date : DATE
    status : VARCHAR(20)
    is_active : BOOLEAN
    is_recipe : BOOLEAN
    minimum : DECIMAL(15,5)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "material_details" as material_details {
    *id : UUID <<PK>>
    --
    material_id : UUID <<FK>>
    unit_id : UUID <<FK>>
    price : DECIMAL(15,2)
    is_main : BOOLEAN
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "material_batches" as material_batches {
    *id : UUID <<PK>>
    --
    material_id : UUID <<FK>>
    unit_id : UUID <<FK>>
    batch_number : VARCHAR(255)
    date : DATE
    batch_quantity : DECIMAL(15,2)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "product_compositions" as product_compositions {
    *id : UUID <<PK>>
    --
    product_id : UUID <<FK>>
    material_id : UUID <<FK>>
    unit_id : UUID <<FK>>
    material_quantity : DECIMAL(8,2)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "ingredient_categories" as ingredient_categories {
    *id : UUID <<PK>>
    --
    name : VARCHAR(50)
    description : VARCHAR(255)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "ingredient_category_details" as ingredient_category_details {
    *id : UUID <<PK>>
    --
    ingredient_category_id : UUID <<FK>>
    material_id : UUID <<FK>>
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "suppliers" as suppliers {
    *id : UUID <<PK>>
    --
    name : VARCHAR(50)
    description : VARCHAR(255)
    contact_name : VARCHAR(50)
    phone : VARCHAR(20)
    street : VARCHAR(255)
    landmark : VARCHAR(255)
    maps_link : VARCHAR(500)
    image : VARCHAR(255)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "expenses" as expenses {
    *id : UUID <<PK>>
    --
    expense_number : VARCHAR(255) <<UNIQUE>>
    expense_date : DATE
    end_date : DATE
    supplier_id : UUID <<FK>>
    note : VARCHAR(255)
    status : VARCHAR(255)
    grand_total_expect : DECIMAL(10,2)
    grand_total_actual : DECIMAL(10,2)
    is_start : BOOLEAN
    is_finish : BOOLEAN
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "expense_details" as expense_details {
    *id : UUID <<PK>>
    --
    expense_id : UUID <<FK>>
    material_id : UUID <<FK>>
    unit_id : UUID <<FK>>
    quantity_expect : DECIMAL(15,5)
    quantity_get : DECIMAL(15,5)
    is_quantity_get : BOOLEAN
    price_expect : DECIMAL(10,2)
    price_get : DECIMAL(10,2)
    total_expect : DECIMAL(10,2)
    total_actual : DECIMAL(10,2)
    expiry_date : DATE
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "productions" as productions {
    *id : UUID <<PK>>
    --
    production_number : VARCHAR(255)
    transaction_id : UUID <<FK>>
    method : VARCHAR(255)
    date : DATE
    time : TIME
    start_date : DATE
    end_date : DATE
    note : VARCHAR(255)
    status : VARCHAR(20)
    is_start : BOOLEAN
    is_finish : BOOLEAN
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "production_details" as production_details {
    *id : UUID <<PK>>
    --
    production_id : UUID <<FK>>
    product_id : UUID <<FK>>
    quantity_plan : DECIMAL(8,0)
    quantity_get : DECIMAL(8,0)
    quantity_fail : DECIMAL(8,0)
    cycle : DECIMAL(2,0)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "production_workers" as production_workers {
    *id : UUID <<PK>>
    --
    production_id : UUID <<FK>>
    user_id : UUID <<FK>>
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "hitungs" as hitungs {
    *id : UUID <<PK>>
    --
    user_id : UUID <<FK>>
    hitung_number : VARCHAR(30) <<UNIQUE>>
    action : VARCHAR(50)
    note : VARCHAR(255)
    status : VARCHAR(20)
    hitung_date : DATE
    hitung_date_finish : DATE
    is_start : BOOLEAN
    is_finish : BOOLEAN
    grand_total : DECIMAL(15,2)
    loss_grand_total : DECIMAL(15,2)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "hitung_details" as hitung_details {
    *id : UUID <<PK>>
    --
    hitung_id : UUID <<FK>>
    material_id : UUID <<FK>>
    unit_id : UUID <<FK>>
    quantity_system : DECIMAL(15,5)
    quantity_actual : DECIMAL(15,5)
    quantity_difference : DECIMAL(15,5)
    price : DECIMAL(15,2)
    total_loss : DECIMAL(15,2)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "inventory_logs" as inventory_logs {
    *id : UUID <<PK>>
    --
    material_id : UUID <<FK>>
    material_batch_id : UUID <<FK>>
    user_id : UUID <<FK>>
    action : VARCHAR(255)
    quantity_change : DECIMAL(15,4)
    quantity_after : DECIMAL(15,4)
    reference_type : VARCHAR(255)
    reference_id : VARCHAR(255)
    note : TEXT
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "refunds" as refunds {
    *id : UUID <<PK>>
    --
    transaction_id : UUID <<FK>>
    reason : VARCHAR(255)
    proof_image : VARCHAR(255)
    refund_method : VARCHAR(255)
    payment_channel_id : UUID <<FK>>
    account_number : VARCHAR(255)
    total_amount : DECIMAL(10,0)
    refund_by_shift : UUID <<FK>>
    refunded_at : DATETIME
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "store_profiles" as store_profiles {
    *id : UUID <<PK>>
    --
    logo : VARCHAR(255)
    name : VARCHAR(255)
    tagline : VARCHAR(255)
    type : VARCHAR(255)
    banner : VARCHAR(255)
    product : VARCHAR(255)
    description : TEXT
    building : VARCHAR(255)
    location : VARCHAR(255)
    address : VARCHAR(255)
    contact : VARCHAR(255)
    email : VARCHAR(255)
    website : VARCHAR(255)
    social_instagram : VARCHAR(255)
    social_facebook : VARCHAR(255)
    social_whatsapp : VARCHAR(255)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "store_documents" as store_documents {
    *id : UUID <<PK>>
    --
    document_name : VARCHAR(255)
    document_number : VARCHAR(255)
    document_file : VARCHAR(255)
    valid_from : DATE
    valid_until : DATE
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "activity_log" as activity_log {
    *id : BIGINT <<PK>>
    --
    log_name : VARCHAR(255)
    description : TEXT
    subject_type : VARCHAR(255)
    subject_id : UUID
    causer_type : VARCHAR(255)
    causer_id : UUID
    properties : JSON
    event : VARCHAR(255)
    batch_uuid : UUID
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

' ==========================================
' RELASI
' ==========================================

materials ||--o{ material_details
materials ||--o{ material_batches
materials ||--o{ product_compositions
materials ||--o{ expense_details
materials ||--o{ ingredient_category_details
materials ||--o{ hitung_details
materials ||--o{ inventory_logs

material_batches ||--o{ inventory_logs

ingredient_categories ||--o{ ingredient_category_details

suppliers ||--o{ expenses
expenses ||--o{ expense_details

productions ||--o{ production_details
productions ||--o{ production_workers

hitungs ||--o{ hitung_details

@enduml
